name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -XPOST 'https://discord.com/api/webhooks/914789995418648616/upbP9tM-vOIwQXng_ZlPIACJrzmMEMgISu15NfSolQCmGXhKw_o5Wf_mI0X989Oz_I1b' -H 'Content-Type: application/json' -d '{"content": "un push a été effectuer sur la branche main"}'